server:
  port: 8888

spring:
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 20MB
  main:
    banner-mode: "off"
    allow-circular-references: true
  application:
    name: myBlog
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:13306/blog?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: psx0211
  redis:
    host: localhost
    port: 6379
mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      table-prefix: ms_
    banner: false